### ISSUE TITLE
Issue in  bot groups

### ISSUE THREAD

**Issue by NotWarLord** [noemica/cog-minder#15]
Gave an error and had to reload the page. Was unable to see any other content but the name on the top still changed. Ex. Tap About and the name was cog-minder about then Tap on wiki and then cog-minder wiki but still the same screen rather odd. Anyway I had meant to click on wizards In the bot groups but I could not replicate it so idk

TypeError: Cannot read properties of undefined (reading 'content') at q (https://noemica.github.io/cog-minder/assets/WikiPage-uiLE_E3T.js:1165:1771) at Ce (https://noemica.github.io/cog-minder/assets/WikiPage-uiLE_E3T.js:1165:4782) at at (https://noemica.github.io/cog-minder/assets/WikiPage-uiLE_E3T.js:1168:17884) at ha (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:38:19518) at du (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:3139) at Cm (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:44705) at Sm (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:39703) at j0 (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:39631) at Hi (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:39485) at Cu (https://noemica.github.io/cog-minder/assets/index-mA6cqarB.js:40:35864

IMPORTANT  this is for the devs, clicking on random links is a bad idea for many reasons this is my first error so I don not know how to remove them

**Comment by noemica** [comment]
Thanks for the report. This is an interesting error, it looks like it failed to load the wiki data and then crashed after that. So after a refresh the error went away and things worked properly? Or can you still not load the wiki or other pages?

If it still doesn't load correctly, could you tell me what browser you're using?

**Comment by NotWarLord** [comment]
It did work after I refreshed the page, and I actually came here to edit my report because i realized that it probably had something to do with connection and not the website (oops). Thanks for replying so fast and for this great resource! 
*I'm assuming that it is all and will close this.

**Comment by noemica** [comment]
I took another look at this when somebody else ran into this same issue. This issue has to do with the way the website gets updated. I ended up adding update detection with an icon for "please reload the page" that shows in the top right, and if an error like this pops up again it will reload the page first. Hopefully that means if you run into this issue again it will fix itself on the reload and not be too much of a hassle.
