### ISSUE TITLE
Second [[Comment]] tag fails to parse when using two [[Comment]][[/Comment]] tags at the same content level

### ISSUE THREAD

**Issue by GitPerseus** [noemica/cog-minder#22]
When previewing the changes to an article, if there are two [[Comment]][[/Comment]] tags at the same content level (as in, at the top level, or in the same element of a list or table), then the the following error is returned : 
> Found mismatched end tag /Comment with expected tag undefined: section starting with "[[/Comment]]"

The following two cases will cause the error : 
>[[Comment]][[/Comment]][[Comment]][[/Comment]]

>[[Comment]]First[[/Comment]]
>[[Heading]]doesn't prevent the bug[[/Heading]]
>[[Comment]]Second[[/Comment]]

But this won't cause the error : 
> [[Comment]]This is fine.[[/Comment]]
> [[List]]
> [[Comment]]This isn't at the same content level.[[/Comment]]
> |
> [[Comment]]This is in a different element of the list, so this is still fine![[/Comment]]
> [[/List]]

**Comment by noemica** [comment]
Whoops, fixed this silly mistake. Thanks for the report.
